# Generated by Django 5.2.4 on 2025-08-01 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="expertprofile",
            name="featured",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="podcastprofile",
            name="featured",
            field=models.BooleanField(default=False),
        ),
    ]
