# Generated by Django 5.1.7 on 2025-08-01 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_expertprofile_category_podcastprofile_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='expertprofile',
            name='image',
            field=models.ImageField(blank=True, help_text='Upload your profile picture', null=True, upload_to='expert_images/'),
        ),
        migrations.AddField(
            model_name='podcastprofile',
            name='image',
            field=models.ImageField(blank=True, help_text='Upload your podcast cover image', null=True, upload_to='podcast_images/'),
        ),
    ]
