# Generated by Django 5.1.7 on 2025-08-01 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_expertprofile_image_podcastprofile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='expertprofile',
            name='is_approved',
            field=models.BooleanField(default=False, help_text='Admin approval status'),
        ),
        migrations.AddField(
            model_name='podcastprofile',
            name='is_approved',
            field=models.BooleanField(default=False, help_text='Admin approval status'),
        ),
    ]
