# Generated by Django 5.1.7 on 2025-08-04 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_expertprofile_is_approved_podcastprofile_is_approved'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expertprofile',
            name='is_approved',
        ),
        migrations.RemoveField(
            model_name='podcastprofile',
            name='is_approved',
        ),
        migrations.AddField(
            model_name='expertprofile',
            name='email',
            field=models.EmailField(blank=True, help_text='Your professional email address', max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='expertprofile',
            name='instagram_url',
            field=models.URLField(blank=True, help_text='Your Instagram profile URL', null=True),
        ),
        migrations.AddField(
            model_name='expertprofile',
            name='linkedin_url',
            field=models.URLField(blank=True, help_text='Your LinkedIn profile URL', null=True),
        ),
        migrations.AddField(
            model_name='expertprofile',
            name='twitter_url',
            field=models.URLField(blank=True, help_text='Your Twitter/X profile URL', null=True),
        ),
        migrations.AddField(
            model_name='expertprofile',
            name='website_url',
            field=models.URLField(blank=True, help_text='Your personal or business website', null=True),
        ),
    ]
