# Generated by Django 5.1.7 on 2025-08-05 11:21

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_expertprofile_is_approved_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expertprofile',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, help_text='Upload your profile picture', max_length=255, null=True, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='podcastprofile',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, help_text='Upload your podcast cover image', max_length=255, null=True, verbose_name='image'),
        ),
    ]
